### PR TITLE
Refactor to use rspec filtering

### PR DESCRIPTION
**Pull request by djberg96**
Just a draft PR for now to replace some inline logic with rspec filters and tags. The tags are useful for both config and for the command line.

I'm also tweaking the Jruby handling a bit to be more generic since there's now also Truffleruby.

### CODE REVIEW

**Comment by djberg96** [comment]
@sferik What do you think of this approach?

**Comment by sferik** [comment]
I like this approach. I'll be happy to merge it when the build failures are fixed.

**Comment by sferik** [comment]
Does this supersede https://github.com/intridea/multi_json/pull/213? If so, can you close that PR?

**Comment by djberg96** [comment]
@sferik Thanks. I'm still working out some JRuby/Truffleruby things, probably shoulda left it as a draft. I'll ping you when I think it's ready.

**Comment by sferik** [comment]
Looks like tests are passing. Is this ready for review now?

**Comment by djberg96** [comment]
@sferik I could tinker with it some more, but I guess it's ready.

The main issue was that the tags weren't as useful as I hoped since the `require` statements are evaluated first, and blow up with or without tags. I think they'd have to be removed from the file list first, but that can be done in a future refactor.

Why was this closed?

**Comment by sferik** [comment]
Oops. I must have accidentally hit “Comment and Close” instead of “Comment”. Pressing “Reopen and comment” now. ☺️

**Pull request merged**
