### PR TITLE
Remove nsjsonserialization

### PR DESCRIPTION
**Pull request by djberg96**
Upon further review, nsjsonserialization was for MacRuby, which is long defunct:

https://github.com/MacRuby/MacRuby/blob/master/README.rdoc

https://developer.apple.com/documentation/foundation/nsjsonserialization

There is something called [RubyMotion](http://www.rubymotion.com/), but beyond some failed tinkering I've never really tried it, nor am I sure it would use the nsjsonserialization adapter anyway, as it's apparently more of a cross-platform environment for mobile apps. So, unless there's any objection, I think it's best to just remove it.

~~While I was here I fixed the Rakefile. There is no "standard/rake" that I'm aware of, and that fails for me locally. It's just "rake".~~

### CODE REVIEW

**Comment by sferik** [comment]
`standard/rake` comes from the `standard` gem, which is in the `Gemfile` and should not cause an error. What error were you seeing? Does it go away if you run `bundle exec rake`?

**Comment by sferik** [comment]
In general, pull requests should only do one thing. If all this PR did was remove NSJSONSerialization, it would already be merge.

**Comment by sferik** [comment]
Can you please fixup these commits so there's only one?

**Comment by djberg96** [comment]
@sferik ok done

**Pull request merged**
